// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.

pub fn solve() {

    let limit = 4000000;
    let mut t1 = 1;
    let mut t2 = 2;
    let mut sum = 2; // initialize with t2, since it is even

    loop {
        let t3 = t1 + t2;

        if t3 > limit { break; }

        if t3 % 2 == 0 {
            sum += t3
        }

        t1 = t2;
        t2 = t3;
    }

    println!("Sum is {}", sum);
}
